directory: ~/Music/beets
library: ~/Music/beets/library.db

import:
  # Write metadata to files. Copy files from the import directory, don't move
  # them.
  write: yes
  copy: yes
  move: no

  autotag: yes
  timid: no

plugins:
  - fetchart
  - embedart
  - convert
  - lastgenre
  - scrub
  - unimported

fetchart:
  auto: yes
  cautious: yes

embedart:
  auto: yes

lyrics:
  auto: yes

convert:
  format: aac
  auto: no
  dest: ~/Music/beets_converted
  never_convert_lossy_files: yes
  formats:
    aac:
      command: ffmpeg -i $source -y -vn -acodec aac -aq 2 $dest
      extension: m4a

lastgenre:
  force: no

unimported:
  ignore_extensions:
    - jpg
    - png
    - log
    - cue
    - txt
    - pdf
