# https://docs.noctalia.dev/v5/configuration/
[shell]
launch_apps_as_systemd_services = true
font_family = "Overpass"

[shell.panel]
open_near_click_control_center = true

[shell.launcher]
categories = false

[theme]
mode    = "dark"
source  = "builtin"
builtin = "Catppuccin"

[wallpaper]
enabled   = true
fill_mode = "crop"
directory = "/home/alex/Pictures/Wallpapers"

[backdrop]
enabled = true

[location]
auto_locate = false
address     = ""
latitude    = 53.4
longitude   = -3.0

[nightlight]
enabled            = true
temperature_day    = 6500
temperature_night  = 4000

[notification]
enable_daemon = true

[lockscreen]
enabled = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "clock_main", "lockscreen-widget-0000000000000002" ]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget.clock_main]
box_height = 120.0
box_width = 360.0
cx = 1280.0
cy = 128.0
output = "DP-3"
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.clock_main.settings]
background = true
background_opacity = 0.59999999999999998
center_text = true
clock_style = "digital"
color = "on_surface"
format = "{:%H:%M}"
shadow = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
box_height = 70.0
box_width = 400.0
cx = 1280.0
cy = 1331.0
output = "DP-3"
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "compact"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = false
show_weather = true

[lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
box_height = 48.0
box_width = 400.0
cx = 1280.0
cy = 1272.0
output = "DP-3"
rotation = 0.0
type = "audio_visualizer"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
background = false
bands = 64
centered = false
color_1 = "hover"
color_2 = "hover"
mirrored = true
show_when_idle = false

[idle.behavior.lock]
timeout = 300
action  = "lock"
enabled = true

[idle.behavior.screen-off]
timeout = 330
action  = "screen_off"
enabled = true

[keybinds]
up   = [ "up", "ctrl+p" ]
down = [ "down", "ctrl+n" ]

[control_center]
sidebar = "compact"
hidden_tabs = [ "monitor", "power","network", "bluetooth"]

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "session"

[bar.main]
start  = [ "launcher", "workspaces", "active_window" ]
center = []
end    = [ "tray", "volume", "notifications", "control-center", "clock"]
margin_ends = 0
widget_spacing = 12
radius = 0

[osd]
position = "top_right"

[widget.volume]
show_label = false

[widget.workspaces]
active_pill_size = 1.5

[widget.clock]
format = "{:%a %d %b %H:%M}"

[widget.control-center]
glyph = "adjustments-horizontal"

[widget.notifications]
hide_when_no_unread = true
