start-at-login = false

# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []
after-startup-command = [
    'exec-and-forget borders active_color=0xff8839ef width=4',
]

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[exec.env-vars]
PATH = '${HOME}/.nix-profile/bin:${PATH}'

# Sadly aliases for key combos aren't supported yet (nikitabobko/AeroSpace#224)
#
# Keeping these here for reference.
[key-mapping.key-notation-to-key-code]
# Colemak mapping
q = 'q'
w = 'w'
f = 'e'
p = 'r'
g = 't'
j = 'y'
l = 'u'
u = 'i'
y = 'o'
semicolon = 'p'
leftSquareBracket = 'leftSquareBracket'
rightSquareBracket = 'rightSquareBracket'
backslash = 'backslash'

a = 'a'
r = 's'
s = 'd'
t = 'f'
d = 'g'
h = 'h'
n = 'j'
e = 'k'
i = 'l'
o = 'semicolon'
quote = 'quote'

z = 'z'
x = 'x'
c = 'c'
v = 'v'
b = 'b'
k = 'n'
m = 'm'
comma = 'comma'
period = 'period'
slash = 'slash'

# Sadly aliases for key combos aren't supported yet (nikitabobko/AeroSpace#224)
#
#     hyper = "alt-shift-ctrl-cmd"
#     meh = "alt-shift-ctrl"
#     prefix = "alt-ctrl"

[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 4
outer.bottom = 4
outer.top = 4
outer.right = 4

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
ctrl-alt-enter = 'exec-and-forget osascript -e "tell application \"Ghostty\" to activate"'

ctrl-alt-slash = 'layout tiles horizontal vertical'
ctrl-alt-comma = 'layout accordion horizontal vertical'
ctrl-alt-period = 'layout tiling floating'
ctrl-alt-f = 'fullscreen'

ctrl-alt-h = 'focus --boundaries all-monitors-outer-frame left'
ctrl-alt-j = 'focus --boundaries all-monitors-outer-frame down'
ctrl-alt-k = 'focus --boundaries all-monitors-outer-frame up'
ctrl-alt-l = 'focus --boundaries all-monitors-outer-frame right'

ctrl-alt-shift-h = 'move left'
ctrl-alt-shift-j = 'move down'
ctrl-alt-shift-k = 'move up'
ctrl-alt-shift-l = 'move right'

ctrl-alt-minus = 'resize smart -50'
ctrl-alt-equal = 'resize smart +50'
ctrl-alt-shift-equal = 'balance-sizes'

ctrl-alt-1 = 'workspace 1'
ctrl-alt-2 = 'workspace 2'
ctrl-alt-3 = 'workspace 3'
ctrl-alt-4 = 'workspace 4'
ctrl-alt-5 = 'workspace 5'
ctrl-alt-6 = 'workspace 6'

ctrl-alt-shift-1 = 'move-node-to-workspace 1'
ctrl-alt-shift-2 = 'move-node-to-workspace 2'
ctrl-alt-shift-3 = 'move-node-to-workspace 3'
ctrl-alt-shift-4 = 'move-node-to-workspace 4'
ctrl-alt-shift-5 = 'move-node-to-workspace 5'
ctrl-alt-shift-6 = 'move-node-to-workspace 6'

cmd-ctrl-tab = 'workspace-back-and-forth'
ctrl-alt-tab = 'move-workspace-to-monitor --wrap-around next'

ctrl-alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout

ctrl-alt-h = ['join-with left', 'mode main']
ctrl-alt-j = ['join-with down', 'mode main']
ctrl-alt-k = ['join-with up', 'mode main']
ctrl-alt-l = ['join-with right', 'mode main']

# Window Rules

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.freron.MailMate'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.culturedcode.ThingsMac'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.apple.iphonesimulator'
run = 'layout floating'
