# Taps
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/services'
tap 'homebrew/science'

# Languages
brew 'ruby'
brew 'python'
brew 'python3'
brew 'go'

# Core Utilities
brew 'mas'

brew 'ag'
brew 'coreutils'
brew 'fish'
brew 'htop'
brew 'hugo'
brew 'nmap'
brew 'pigz'
brew 'pxz'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'xz'

# Dev Tools
brew 'carthage'
brew 'git'
brew 'node'
brew 'vim'
brew 'mysql'

# Security
brew 'gnupg'
brew 'gnupg2'
brew 'gpg-agent'
brew 'pinentry-mac'

# Other Tools
brew 'aspell'
brew 'ffmpeg', args: ['with-x265']
brew 'ledger'
brew 'pandoc'
brew 'youtube-dl'

# Python Libraries
brew 'matplotlib', args: ['with-python3', 'with-cairo', 'with-ghostscript']
brew 'numpy', args: ['with-python3']
brew 'scipy', args: ['with-python3']

# macOS Software
cask 'anki'
cask 'appcleaner'
cask 'appcode'
cask 'arq'
cask 'calibre'
cask 'daisydisk'
cask 'dash'
cask 'db-browser-for-sqlite'
cask 'dropbox'
cask 'emacs'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'handbrake'
cask 'hex-fiend'
cask 'keka'
cask 'mysqlworkbench'
cask 'qlstephen'
cask 'sketch'
cask 'smcfancontrol'
cask 'spectacle'
cask 'spotify'
cask 'subler'
cask 'superduper'
cask 'transmission'
cask 'transmit'
cask 'viscosity'
cask 'vlc'
cask 'vmware-fusion'

mas '1Blocker', id: 1107421413
mas '1Password', id: 443987910
mas 'Amphetamine', id: 937984704
mas 'Deliveries', id: 924726344
mas 'Marked', id: 890031187
mas 'PDF Expert', id: 1055273043
mas 'Reeder', id: 880001334
mas 'Slack', id: 803453959
mas 'Things 3', id: 904280696

# Fonts
cask 'font-cabin'
cask 'font-cardo'
cask 'font-fira-code'
cask 'font-fira-mono'
cask 'font-fira-sans'
cask 'font-iosevka'
cask 'font-lato'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
