alias dropdev "cd ~/Dropbox/Documents/Development/"
alias alexjohnj "cd ~/Dropbox/Documents/Development/Web/alexjohnj/"
alias geographyas "cd ~/Dropbox/Documents/Development/Web/geographyas/"
alias report-project "cd /Users/alex/Dropbox/Documents/Uni/Fundamentals\ of\ Geophysics/Tutorials/Seismic\ Refraction\ Report"
alias uni-work "cd /Users/alex/Dropbox/Documents/Uni"
