set nocompatible
syntax on
set encoding=utf-8
set showcmd
filetype plugin indent on
inoremap fd <Esc>

"" Whitespace Configuration
set wrap
set formatoptions=tcq
set tabstop=2 shiftwidth=2
set expandtab
set backspace=indent,eol,start

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

"" Key Mappings
let mapleader = " "
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

"" Window Management (set to match Emacs)
nnoremap <Leader>ws :split<cr>
nnoremap <Leader>wv :vsplit<cr>
nnoremap <Leader>wc :close<cr>
nnoremap <Leader>wC :only<cr>
nnoremap <Leader>wj :wincmd j<cr>
nnoremap <Leader>wh :wincmd h<cr>
nnoremap <Leader>wl :wincmd l<cr>
nnoremap <Leader>wk :wincmd k<cr>
nnoremap <Leader>wJ <C-W>J
nnoremap <Leader>wK <C-W>K
nnoremap <Leader>wH <C-W>H
nnoremap <Leader>wL <C-W>L
nnoremap <Leader>w= <C-W>=
nnoremap <Leader>ww <C-W>w

"" Other stuff
set autoread " Autoreloads unedited files if they're edited elsewhere

"" vim-commentary
autocmd FileType matlab setlocal commentstring=%\ %s

if has('gui_running')
  set background=dark
  set guifont=Consolas:h11
  colorscheme base16-eighties
endif
