# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a6ef4f00-3674-4b46-b5fc-86773cc960f6";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0057a4f0-bd36-418e-8e6e-9ddd41f42f51".device =
    "/dev/disk/by-uuid/0057a4f0-bd36-418e-8e6e-9ddd41f42f51";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/84DE-3944";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/c4f35327-634c-4a37-a658-8ebd9453f8b4"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
