#!/usr/bin/env fish
#
# Script for updating ports installed on my FreeBSD server while keeping them
# locked for pkg upgrades.
#
# Create a file in your home directory called ".portfile" that contains the name
# of the packges installed from ports separated by newlines.

set -l PORTFILE "$HOME/.portfile"
set -l PORTS (cat $PORTFILE)

for port in $PORTS
  sudo pkg unlock -y "$port"
end

echo $PORTS | sudo xargs portmaster --update-if-newer

for port in $PORTS
  sudo pkg lock -y "$port"
end
